### ISSUE TITLE
Expandable Menu - Popcorn Foundation (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/popcorn-foundation#12]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2982%3A38735

##Deliverable
- 1 x Desktop top nav
- 1 x Mobile expandable menu (For narrow screens to mobiles)

## Key Development Requirements
- Clean, lean, and organized code
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).
- The expandable menu and the entire UX flow should be adaptive with fluid transition across all mobile devices. (*We have this ready build for our main site. Please reach out to Manny for a duplicate and work from there.)

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image References
<img width="356" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631383130353030616666373336306439636364356462332f33623238663632342d366531612d346362372d393064332d666466623036656339353539" src="https://user-images.githubusercontent.com/93581054/142659507-c1096ee3-3957-446e-a376-d88a29ed77d7.png">

**Comment by mefuru** [comment]
Will need to incorporate the animation from the gitcoin bounty at some point
