### ISSUE TITLE
Website finalization

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/popcorn-foundation#25]
## To-do

- Hide partners page as we don't need it at this moment
- Make footer divider gray 900 at 10% so it is more subtle in appearance. (See reference below)

## Image Reference
![Screen Shot 2022-01-06 at 11.39.19 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d736c375-3f11-4997-899f-c8d13c642f9b)

**Comment by FanFanDAO** [comment]
@anthonymartin if there is anything else to be finalized please let us know.

**Comment by anthonymartin** [comment]
There's also a typo on mobile view on the front page. Poporn -> Popcorn
